version: '3.8'
services:
  db:
    build: ./db
    container_name: loan_db
    networks:
      - loan-network
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  api:
    build: ./backend
    container_name: loan_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/swtp
      - SPRING_DATASOURCE_USERNAME=root
    networks:
      - loan-network

  ui:
    image: "nginx:1.25.3-alpine-slim"
    container_name: loan_frontend
    ports:
      - "63342:80"
    volumes:
      - ./ui:/usr/share/nginx/html
    networks:
      - loan-network

networks:
  loan-network:
    name: "loan-network"
    driver: bridge