
services:
  db:
    build: ./db
    container_name: loan_db
    networks:
      - loan-network
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  backend:
    build: ./backend
    container_name: loan_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/swtp
      - SPRING_DATASOURCE_USERNAME=root
    networks:
      - loan-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      REACT_APP_API_BASE_URL: /api/benutzer
    depends_on:
      - backend
    networks:
      - loan-network

networks:
  loan-network:
    name: "loan-network"
    driver: bridge